import {intentSchema} from '@/lib/intent-schema';
import {chatWithLlm,startChatWithLlm,recommendSyntheticOffers,explainStarterSearchWithLlm,LlmError,llmStatus,type StarterOfferQuery,type StarterDialogueAction} from '@/lib/llm';
import {database,authIdentity,mutationGuard,failure} from '@/lib/server';
import {initialState,type State,type Trip,type PreferenceDimension,type Intent,type StarterConversation,type StarterSearchFilters,type StarterSelectedOffer} from '@/lib/model';
import {retrieveSyntheticOffers} from '@/lib/synthetic-flights';
import {searchStarterFlights,getStarterFlightById,getStarterRouteCount,type StarterFlightCandidate,type StarterFlightSearchResult} from '@/lib/starter-flight-search';
import {z} from 'zod';
const intent=intentSchema;
function synthetic(t:Intent){return retrieveSyntheticOffers(t)}
function makeOffers(t:Intent){return synthetic(t).offers}
function retrievalSummary(t:Intent){return synthetic(t).summary}
function hydrateSyntheticTrips(s:State){for(const trip of s.trips){const legacy=!trip.retrieval||trip.offers.some(o=>!o.source);if(legacy){const r=synthetic(trip);trip.offers=r.offers;trip.retrieval=r.summary;delete trip.aiRecommendation;}}}
async function consumeLlmQuota(owner:string){const minute=Math.floor(Date.now()/60000),day=new Date().toISOString().slice(0,10);const quota=await database().prepare(`INSERT INTO llm_limits(owner,minute,count,day,daily_count) VALUES (?,?,1,?,1)
 ON CONFLICT(owner) DO UPDATE SET minute=excluded.minute,count=CASE WHEN llm_limits.minute=excluded.minute THEN llm_limits.count+1 ELSE 1 END,day=excluded.day,daily_count=CASE WHEN llm_limits.day=excluded.day THEN llm_limits.daily_count+1 ELSE 1 END
 WHERE (llm_limits.minute!=excluded.minute OR llm_limits.count<6) AND (llm_limits.day!=excluded.day OR llm_limits.daily_count<100) RETURNING owner`).bind(owner,minute,day).first();if(!quota)throw new LlmError('LLM_USER_LIMIT','Bạn đã đạt giới hạn chat (6 lượt/phút hoặc 100 lượt/ngày). Vui lòng thử lại sau.',429);}
function ensureStarter(s:State):StarterConversation{if(!s.starter)s.starter={messages:[],draft:{},searchFilters:{},phase:'collecting',selectedOfferId:null,selectedOffer:null};s.starter.searchFilters??={};s.starter.phase??='collecting';if(s.starter.selectedOfferId&&!s.starter.selectedOffer){const c=getStarterFlightById(s.starter.selectedOfferId,s.starter.draft.passengers??1);if(c)s.starter.selectedOffer=selectedSnapshot(c);}return s.starter;}
function starterCandidate(s:State){const d=s.starter?.draft||{};return {...d,name:(d.name||`${d.from||'Trip'} → ${d.to||'Trip'}`).slice(0,70),passengers:d.passengers??1,baggage:d.baggage??s.profile.baggage??23,transit:d.transit??24,seat:d.seat||s.profile.seat||'No preference'};}
function starterReady(s:State){return intent.safeParse(starterCandidate(s)).success;}
function normText(text:string){return text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function affirmative(text:string){const n=normText(text);return /^(co|duoc|ok|okay|yes|yep|dong y|chuyen sang|chuyen sang lua chon tot nhat|lay cai do|chon cai do|duoc chuyen sang cho toi)$/.test(n)||/^(co|duoc|ok|yes)\b/.test(n);}
function negative(text:string){const n=normText(text);return /^(khong|khong can|thoi|no|nope|cancel|bo qua)$/.test(n);}
function statusQuestion(text:string){const n=normText(text);return /\b(xong chua|xong roi chua|da xong chua|da doi chua|status|done yet|is it done)\b/.test(n);}
function selectionCommand(text:string){const n=normText(text);return /\b(chuyen sang|chon|lay)\b.*\b(lua chon|chuyen|cai do|tot nhat)\b/.test(n)||/\bselect\b.*\b(best|option)\b/.test(n);}
function clearSelectionIfIntentChanged(st:StarterConversation,patch:Partial<Intent>){if(['from','to','start'].some(k=>k in patch)){st.selectedOfferId=null;st.selectedOffer=null;st.pendingSuggestion=undefined;st.lastSearch=undefined;st.phase='collecting';}}
function mergeSearchFilters(st:StarterConversation,q:StarterOfferQuery):StarterSearchFilters{
 const f:{[key:string]:unknown}={...(st.searchFilters||{})};
 for(const key of q.clearFilters||[])delete f[key];
 for(const key of ['maxPrice','maxTransit','minBaggage','directOnly','transitVia'] as const){const value=q[key];if(value!==undefined&&value!==null)f[key]=value;}
 if(q.sortBy)f.sortBy=q.sortBy;if(q.limit)f.limit=q.limit;
 st.searchFilters=f as StarterSearchFilters;return st.searchFilters;
}
function currentQuery(st:StarterConversation,requested=true):StarterOfferQuery{return {requested,maxPrice:st.searchFilters?.maxPrice??null,maxTransit:st.searchFilters?.maxTransit??null,minBaggage:st.searchFilters?.minBaggage??null,directOnly:st.searchFilters?.directOnly??null,transitVia:st.searchFilters?.transitVia??null,sortBy:st.searchFilters?.sortBy||'best',limit:st.searchFilters?.limit||3,clearFilters:[]};}
function buildStarterSearch(s:State):Parameters<typeof searchStarterFlights>[0]|null{const d=s.starter?.draft,f=s.starter?.searchFilters;if(!d?.from||!d?.to)return null;return {from:d.from,to:d.to,departureDate:d.start||null,passengers:d.passengers??1,maxPrice:f?.maxPrice??null,maxTransit:f?.maxTransit??null,minBaggage:f?.minBaggage??null,directOnly:f?.directOnly??null,transitVia:f?.transitVia??null,sortBy:f?.sortBy||'best',limit:f?.limit||3};}
function shortOffer(c:StarterFlightCandidate){const transit=c.stops===0?'bay thẳng':`${Math.round(c.transitMinutes/6)/10}h transit tại ${c.transitCity||c.transitAirport}`;return `**${c.id}** (${c.departureDate}) — AUD ${c.totalPriceAUD.toLocaleString()} · ${c.totalDurationText} · ${transit} · ${c.baggageKg}kg`;}
function selectedSnapshot(c:StarterFlightCandidate):StarterSelectedOffer{return {offerId:c.id,departureDate:c.departureDate,departureTime:c.departureTime,arrivalDate:c.arrivalDate,arrivalTime:c.arrivalTime,routing:c.routing,totalPriceAUD:c.totalPriceAUD,totalDurationText:c.totalDurationText,stops:c.stops,transitAirport:c.transitAirport,transitCity:c.transitCity,transitMinutes:c.transitMinutes,baggageKg:c.baggageKg,selectedAt:new Date().toISOString()};}
function fallbackSearchReply(result:StarterFlightSearchResult){
 if(result.routeRows===0)return 'Dataset demo hiện chưa có record cho route này, nên mình không thể tạo một chuyến giả. Bạn có thể thử route khác có trong dữ liệu.';
 if(result.exactMatches.length){const lines=result.exactMatches.slice(0,3).map((o,i)=>`${i+1}. ${shortOffer(o)}`).join('\n');return `Mình đã tìm xong. Lựa chọn phù hợp nhất theo các điều kiện hiện tại là ${shortOffer(result.exactMatches[0])}.\n\nTop lựa chọn:\n${lines}\n\nĐây là dữ liệu giả lập của prototype, không phải giá/tồn chỗ live của Vietnam Airlines.`;}
 if(result.nearbyMatches.length){const lines=result.nearbyMatches.slice(0,3).map((o,i)=>`${i+1}. ${shortOffer(o)}`).join('\n');return `Không có lựa chọn thỏa toàn bộ điều kiện vào đúng ngày ${result.requestedDate}. Ngày gần đó có:\n\n${lines}\n\nMình đề xuất lựa chọn đầu tiên. Bạn có muốn chuyển ngày đi sang ${result.nearbyMatches[0].departureDate} và chọn chuyến đó không?\n\nĐây là dữ liệu giả lập của prototype.`;}
 if(result.sameDateNearMisses.length){const n=result.sameDateNearMisses[0];return `Không có chuyến thỏa toàn bộ điều kiện vào đúng ngày ${result.requestedDate}. Lựa chọn gần nhất là ${shortOffer(n)}.\nKhông đạt vì: ${n.violations.join(' ')}\nCó thể nới nhỏ nhất bằng cách: ${n.relaxations.join(' ')}\n\nĐây là dữ liệu giả lập của prototype.`;}
 return `Dataset demo có route này nhưng không có record phù hợp với ngày/bộ lọc hiện tại. Mình sẽ không tự bịa chuyến bay. ${result.requestedDate?'Bạn có thể đổi ngày hoặc nới một điều kiện.':''}`;
}
function saveLastSearch(st:StarterConversation,text:string,result:StarterFlightSearchResult){st.lastSearch={query:text,requestedDate:result.requestedDate,exactMatchIds:result.exactMatches.map(x=>x.id),nearbyMatchIds:result.nearbyMatches.map(x=>x.id),nearMissIds:result.sameDateNearMisses.map(x=>x.id),recommendedOfferId:result.recommended?.id||null,filters:{...(st.searchFilters||{})},searchedAt:new Date().toISOString()};if(result.exactMatches.length){st.pendingSuggestion=undefined;st.phase='searching';}else if(result.nearbyMatches.length){const best=result.nearbyMatches[0];st.pendingSuggestion={kind:'switch_departure',offerId:best.id,departureDate:best.departureDate,reason:'No exact-date match; nearest suitable alternative.',filters:{...(st.searchFilters||{})},created:new Date().toISOString()};st.phase='awaiting-confirmation';}else{st.pendingSuggestion=undefined;st.phase='searching';}}
function selectedReply(st:StarterConversation){if(!st.selectedOfferId)return 'Bạn chưa chọn chuyến nào. Mình có thể tìm và xếp hạng các lựa chọn trước.';const c=getStarterFlightById(st.selectedOfferId,st.draft.passengers??1);if(!c)return 'Chuyến đã chọn không còn tồn tại trong dataset demo hiện tại. Mình cần tìm lại.';return `Chuyến đang được chọn là ${shortOffer(c)}. Ngày đi trong Travel Intent hiện là ${st.draft.start||c.departureDate}${st.draft.end?`, ngày về vẫn là ${st.draft.end}`:''}.`;
}
function statusReply(st:StarterConversation){if(st.pendingSuggestion){const c=getStarterFlightById(st.pendingSuggestion.offerId,st.draft.passengers??1);return `Mình đã tìm xong nhưng đang chờ bạn xác nhận. Đề xuất hiện tại là ${c?shortOffer(c):st.pendingSuggestion.offerId}. Nếu đồng ý, chỉ cần nói “có” hoặc “chuyển sang lựa chọn đó”.`; }if(st.selectedOfferId)return `Xong phần chọn chuyến đi. ${selectedReply(st)}`;if(st.lastSearch?.recommendedOfferId){const c=getStarterFlightById(st.lastSearch.recommendedOfferId,st.draft.passengers??1);return `Mình đã tìm xong. Lựa chọn được recommend gần nhất là ${c?shortOffer(c):st.lastSearch.recommendedOfferId}, nhưng bạn chưa xác nhận chọn.`;}return 'Chưa có search hoàn chỉnh để xác nhận. Bạn hãy cho mình route/ngày và yêu cầu tìm chuyến.';}
function reverseLegNote(st:StarterConversation){const from=st.draft.to,to=st.draft.from;if(!from||!to||!st.draft.end)return '';const count=getStarterRouteCount(from,to);return count>0?` Dataset có ${count} record cho chặng về ${from} → ${to}; bạn có thể yêu cầu mình tìm chuyến về ngày ${st.draft.end}.`:` Ngày về ${st.draft.end} vẫn được giữ trong Travel Intent, nhưng dataset demo hiện chưa có record ${from} → ${to}, nên mình chưa thể tìm chặng về mà không bịa dữ liệu.`;}
function acceptSuggestion(st:StarterConversation){const p=st.pendingSuggestion;if(!p)return null;st.draft.start=p.departureDate;st.selectedOfferId=p.offerId;st.searchFilters={...p.filters};st.pendingSuggestion=undefined;st.phase='selected';const c=getStarterFlightById(p.offerId,st.draft.passengers??1);st.selectedOffer=c?selectedSnapshot(c):null;return `Đã xác nhận. Mình đã chuyển ngày đi sang ${p.departureDate} và chọn ${c?shortOffer(c):p.offerId}.${reverseLegNote(st)}`;}
function selectRecommended(st:StarterConversation){const id=st.lastSearch?.recommendedOfferId;if(!id)return null;const c=getStarterFlightById(id,st.draft.passengers??1);if(!c)return null;if(st.lastSearch?.nearbyMatchIds.includes(id)&&st.draft.start!==c.departureDate){st.pendingSuggestion={kind:'switch_departure',offerId:id,departureDate:c.departureDate,reason:'Recommended nearby-date option.',filters:{...(st.searchFilters||{})},created:new Date().toISOString()};return acceptSuggestion(st);}st.selectedOfferId=id;st.selectedOffer=selectedSnapshot(c);st.phase='selected';return `Đã chọn ${shortOffer(c)} làm lựa chọn hiện tại.${reverseLegNote(st)}`;}
async function runStarterSearch(s:State,text:string,q:StarterOfferQuery){const st=ensureStarter(s);mergeSearchFilters(st,q);const filters=buildStarterSearch(s);if(!filters)return {reply:'Mình cần ít nhất điểm đi và điểm đến trước khi tìm trong dataset demo.',result:null};st.phase='searching';const result=searchStarterFlights(filters);saveLastSearch(st,text,result);let reply=await explainStarterSearchWithLlm(text,currentQuery(st,true),result);if(!reply)reply=fallbackSearchReply(result);return {reply,result};}
async function load(id:string,profileName:string){const db=database();await db.prepare('INSERT OR IGNORE INTO workspaces (owner,payload,revision) VALUES (?,?,0)').bind(id,JSON.stringify(initialState(profileName))).run();return (await db.prepare('SELECT payload,revision FROM workspaces WHERE owner=?').bind(id).first()) as {payload:string;revision:number};}
export async function GET(r:Request){try{const identity=await authIdentity(r),row=await load(identity.owner,identity.name),state=JSON.parse(row.payload) as State;hydrateSyntheticTrips(state);return Response.json({state,revision:row.revision,llm:llmStatus(),auth:{kind:identity.kind,name:identity.name,email:identity.email,phone:identity.phone}},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(r:Request){try{mutationGuard(r);const identity=await authIdentity(r),id=identity.owner,b=z.object({action:z.string(),revision:z.number().int(),tripId:z.string().nullable().optional()}).passthrough().parse(await r.json()),row=await load(id,identity.name),s:State=JSON.parse(row.payload);hydrateSyntheticTrips(s);if(typeof s.profile.family!=='boolean')s.profile.family=false;if(b.revision!==row.revision)return Response.json({error:'This trip changed in another tab. Refresh and try again.'},{status:409});let result:any=null;if(!Array.isArray(s.preferenceEvidence))s.preferenceEvidence=[];const t=s.trips.find(x=>x.id===b.tripId);
if(b.action==='create'||b.action==='edit'){const parsed=intent.safeParse(b.intent);if(!parsed.success)throw new Error('VALIDATION:Please check the trip fields, airports and dates.');const data=parsed.data;if(b.action==='edit'){if(!t)throw new Error('VALIDATION:Trip not found.');Object.assign(t,data,{version:t.version+1,offers:makeOffers(data),retrieval:retrievalSummary(data)});delete t.aiRecommendation;delete t.pendingIntent;}else {const trip:Trip={...data,id:crypto.randomUUID(),version:1,status:'draft',offers:makeOffers(data),retrieval:retrievalSummary(data),history:[],messages:[{role:'assistant',text:'I have prepared your travel intent. Review your requirements, then start monitoring. These options were retrieved from a synthetic demo dataset. Live Vietnam Airlines search is not connected.'}]};s.trips.unshift(trip);result={tripId:trip.id};}}
else if(b.action==='starter_chat'){
 const text=z.string().trim().min(1).max(2000).parse(b.text),st=ensureStarter(s);if(!llmStatus().configured)throw new LlmError('LLM_NOT_CONFIGURED','Chat AI chưa được kết nối với Ollama. Hãy làm theo HUONG-DAN-CHAY.md.');
 let reply='',action:StarterDialogueAction='other',offerQuery:StarterOfferQuery=currentQuery(st,false);
 if(st.pendingSuggestion&&affirmative(text)){action='accept_suggestion';reply=acceptSuggestion(st)||'';}
 else if(st.pendingSuggestion&&negative(text)){action='reject_suggestion';st.pendingSuggestion=undefined;st.phase='searching';reply='Được, mình giữ nguyên Travel Intent hiện tại và không chuyển sang đề xuất đó. Bạn có thể đổi điều kiện hoặc yêu cầu tìm lại.';}
 else if(statusQuestion(text)){action='check_status';reply=statusReply(st);}
 else if(selectionCommand(text)&&st.lastSearch?.recommendedOfferId){action='select_recommended';reply=selectRecommended(st)||statusReply(st);}
 else {
  await consumeLlmQuota(id);const answer=await startChatWithLlm(st.draft,st.messages,text,s.profile,st);action=answer.action;offerQuery=answer.offerQuery;clearSelectionIfIntentChanged(st,answer.patch);st.draft={...st.draft,...answer.patch};
  if(action==='accept_suggestion'&&st.pendingSuggestion)reply=acceptSuggestion(st)||answer.reply;
  else if(action==='reject_suggestion'&&st.pendingSuggestion){st.pendingSuggestion=undefined;st.phase='searching';reply='Được, mình không áp dụng đề xuất đó. Bạn có thể yêu cầu tìm phương án khác.';}
  else if(action==='check_status')reply=statusReply(st);
  else if(action==='select_recommended')reply=selectRecommended(st)||answer.reply;
  else if(action==='explain_selected')reply=selectedReply(st);
  else if(action==='search'||action==='compare'||answer.offerQuery.requested){const search=await runStarterSearch(s,text,answer.offerQuery);reply=search.reply;result={...(result||{}),search:search.result};}
  else reply=answer.reply;
 }
 st.messages.push({role:'user',text},{role:'assistant',text:reply});st.messages=st.messages.slice(-40);result={...(result||{}),ready:starterReady(s),draft:st.draft,action,offerQuery,dialogue:{phase:st.phase,pendingSuggestion:st.pendingSuggestion||null,selectedOfferId:st.selectedOfferId||null,selectedOffer:st.selectedOffer||null,searchFilters:st.searchFilters||{},lastSearch:st.lastSearch||null}};
}
else if(b.action==='starter_reset'){delete s.starter;result={reset:true};}
else if(b.action==='starter_confirm'){
 if(!s.starter)throw new Error('VALIDATION:Start a conversation with LIA first.');const parsed=intent.safeParse(starterCandidate(s));if(!parsed.success)throw new Error('VALIDATION:LIA still needs your route, travel window and total AUD budget before creating the trip.');const data=parsed.data;const selected=s.starter.selectedOfferId?getStarterFlightById(s.starter.selectedOfferId,data.passengers):null;const selectedOffer=s.starter.selectedOffer||(selected?selectedSnapshot(selected):null);const selectedMessage=selectedOffer?` You selected ${selectedOffer.offerId} (${selectedOffer.departureDate}, AUD ${selectedOffer.totalPriceAUD}) from the synthetic demo dataset.`:'';const trip:Trip={...data,id:crypto.randomUUID(),version:1,status:'draft',selectedOffer,offers:makeOffers(data),retrieval:retrievalSummary(data),history:[],messages:[...s.starter.messages,{role:'assistant',text:'Travel Intent created.'+selectedMessage+' Live Vietnam Airlines search is not connected.'}]};s.trips.unshift(trip);delete s.starter;result={tripId:trip.id};
}
else if(b.action==='profile'){s.profile={...s.profile,...z.object({name:z.string().trim().min(1).max(60).optional(),member:z.boolean(),personalize:z.boolean(),notifications:z.boolean(),seat:z.enum(['Aisle','Window','No preference']),baggage:z.number().min(0).max(46),family:z.boolean()}).parse(b.profile)};}
else if(b.action==='read'){s.notifications.forEach(n=>n.read=true);}
else {if(!t)throw new Error('VALIDATION:Trip not found.');
if(b.action==='ai_recommend'){if(!llmStatus().configured)throw new LlmError('LLM_NOT_CONFIGURED','Chat AI chưa được kết nối với Ollama.');await consumeLlmQuota(id);t.aiRecommendation=await recommendSyntheticOffers(t,s.profile,s.preferenceEvidence);result=t.aiRecommendation;}
else if(b.action==='preference_feedback'){const parsed=z.object({offerId:z.string().min(1),dimension:z.enum(['price','transit','journey_time','baggage','miles'])}).parse(b);const offer=t.offers.find(o=>o.id===parsed.offerId);if(!offer)throw new Error('VALIDATION:Offer not found.');s.preferenceEvidence=s.preferenceEvidence.filter(e=>!(e.tripId===t.id&&e.offerId===offer.id));s.preferenceEvidence.push({id:crypto.randomUUID(),tripId:t.id,offerId:offer.id,dimension:parsed.dimension as PreferenceDimension,created:new Date().toISOString()});s.preferenceEvidence=s.preferenceEvidence.slice(-100);delete t.aiRecommendation;result={saved:true};}
else if(b.action==='status'){if(!['monitoring','paused','cancelled'].includes(String(b.status)))throw new Error('VALIDATION:Invalid status.');t.status=String(b.status);}
else if(b.action==='delete'){s.trips=s.trips.filter(x=>x.id!==t.id);s.notifications=s.notifications.filter(x=>x.tripId!==t.id);s.bookings=s.bookings.filter(x=>x.tripId!==t.id);s.preferenceEvidence=s.preferenceEvidence.filter(x=>x.tripId!==t.id);}
else if(b.action==='chat'){
 const text=z.string().trim().min(1).max(2000).parse(b.text);if(!llmStatus().configured)throw new LlmError('LLM_NOT_CONFIGURED','Chat AI chưa được kết nối với Ollama. Hãy làm theo HUONG-DAN-CHAY.md.');await consumeLlmQuota(id);const answer=await chatWithLlm(t,text,s.profile,s.preferenceEvidence);t.messages.push({role:'user',text},{role:'assistant',text:answer.reply});t.feedback=text;t.messages=t.messages.slice(-100);delete t.pendingIntent;if(Object.keys(answer.patch).length)t.pendingIntent={id:crypto.randomUUID(),patch:answer.patch,baseVersion:t.version};
}
else if(b.action==='confirm_intent'){
 const pending=t.pendingIntent;if(!pending||b.proposalId!==pending.id||pending.baseVersion!==t.version)throw new Error('VALIDATION:Đề xuất đã thay đổi. Hãy tải lại chuyến đi.');const current=Object.fromEntries(Object.keys(intentSchema.innerType().shape).map(k=>[k,(t as any)[k]]));const merged=intent.parse({...current,...pending.patch});Object.assign(t,merged,{version:t.version+1,offers:makeOffers(merged),retrieval:retrievalSummary(merged)});delete t.aiRecommendation;delete t.pendingIntent;t.messages.push({role:'assistant',text:'Đã lưu Travel Intent theo đề xuất bạn vừa xác nhận. Bạn có thể tiếp tục chỉnh sửa hoặc yêu cầu Qwen xếp hạng các record chuyến bay giả lập đã truy xuất.'});
}
else if(b.action==='dismiss_intent'){if(t.pendingIntent?.id!==b.proposalId)throw new Error('VALIDATION:Đề xuất đã thay đổi.');delete t.pendingIntent;}
else if(b.action==='check'){if(t.status!=='monitoring')throw new Error('VALIDATION:Start monitoring this trip first.');if(t.end<new Date().toISOString().slice(0,10)){t.status='expired';}else {t.offers=makeOffers(t);t.retrieval=retrievalSummary(t);delete t.aiRecommendation;t.checkedAt=new Date().toISOString();const observed=t.offers.slice().sort((a,b)=>a.price-b.price)[0];if(observed){t.history.push({date:new Date().toLocaleDateString('en-AU',{month:'short',day:'numeric'}),price:observed.price});t.history=t.history.slice(-20);}const best=t.offers.filter(o=>o.price<=t.budget).sort((a,b)=>b.score-a.score)[0];if(best&&s.profile.notifications&&!s.notifications.some(n=>n.tripId===t.id&&!n.read)){const reasons=[`within your AUD ${t.budget.toLocaleString()} budget`,`${best.baggage} kg baggage included`,`${best.transit}h transit`];if(s.profile.personalize&&s.profile.seat!=='No preference')reasons.push(`${s.profile.seat.toLowerCase()} seat preference saved`);if(s.profile.family)reasons.push('family preference considered');if(s.profile.member)reasons.push(`${best.miles.toLocaleString()} sample Lotusmiles shown`);s.notifications.unshift({id:crypto.randomUUID(),tripId:t.id,text:`Strong sample match: ${t.from} → ${t.to} for AUD ${best.price.toLocaleString()} · ${reasons.slice(0,4).join(' · ')}.`,read:false});}result={matched:!!best,observedPrice:observed?.price??null};}}
else if(b.action==='demo_fare_observation'){if(t.status!=='monitoring')throw new Error('VALIDATION:Start monitoring this trip first.');const baseline=makeOffers(t);if(!baseline.length)throw new Error('VALIDATION:No illustrative option is available for this intent. Relax transit or baggage constraints first.');const candidate=baseline.find(o=>o.score===100)||baseline[0];const targetBelowBudget=Math.max(50,t.budget-20);const simulatedPrice=Math.max(50,Math.min(candidate.price-70,targetBelowBudget));const simulated={...candidate,id:candidate.id+'-OBS',label:'New observed match · demo',price:simulatedPrice,score:100,source:'simulated-demo-observation' as const};t.offers=[simulated,...baseline.filter(o=>o.id!==candidate.id)];t.checkedAt=new Date().toISOString();t.history.push({date:'Demo now',price:simulated.price});t.history=t.history.slice(-20);s.notifications=s.notifications.filter(n=>n.tripId!==t.id);let notificationCreated=false;if(s.profile.notifications){const reasons=[`now within your AUD ${t.budget.toLocaleString()} budget`,`${simulated.transit}h transit is within your ${t.transit}h limit`,`${simulated.baggage} kg baggage meets your saved requirement`];s.notifications.unshift({id:crypto.randomUUID(),tripId:t.id,text:`Demo fare observation: ${t.from} → ${t.to} for AUD ${simulated.price.toLocaleString()} · ${reasons.join(' · ')}.`,read:false});notificationCreated=true;}result={matched:true,previousPrice:candidate.price,price:simulated.price,notificationCreated,source:'simulated-demo-observation'};}
else if(b.action==='reset_demo_observation'){t.offers=makeOffers(t);t.retrieval=retrievalSummary(t);delete t.aiRecommendation;t.checkedAt=undefined;t.history=[];s.notifications=s.notifications.filter(n=>n.tripId!==t.id);result={reset:true};}
else if(b.action==='booking'){const offer=t.offers.find(o=>o.id===b.offerId);if(!offer||!b.confirmed)throw new Error('VALIDATION:Review and confirm an available offer.');const seat=z.enum(['Aisle','Window','No preference']).parse(b.seat);const extraBag=!!b.extraBag;const booking={id:crypto.randomUUID(),tripId:t.id,offer,seat,extraBag,total:offer.price+(extraBag?65*t.passengers:0),created:new Date().toISOString(),status:'demo-review-complete'};s.bookings.unshift(booking);result=booking;}
else throw new Error('VALIDATION:Unknown action.');}
const update=await database().prepare('UPDATE workspaces SET payload=?,revision=revision+1 WHERE owner=? AND revision=?').bind(JSON.stringify(s),id,row.revision).run();if(!update.meta.changes)return Response.json({error:'Another update was saved. Refresh before retrying.'},{status:409});return Response.json({state:s,revision:row.revision+1,result});}catch(e){if(e instanceof LlmError)return Response.json({error:e.message,code:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'Please check your input.'},{status:400});return failure(e);}}
