import {intentSchema} from '@/lib/intent-schema';
import {chatWithLlm,startChatWithLlm,recommendSyntheticOffers,LlmError,llmStatus,type StarterOfferQuery,type StarterDialogueAction} from '@/lib/llm';
import {database,authIdentity,mutationGuard,failure} from '@/lib/server';
import {initialState,type State,type Trip,type PreferenceDimension,type Intent,type StarterConversation,type StarterSearchFilters,type StarterSelectedOffer,type StarterRoundTripCombo,type StarterLeg} from '@/lib/model';
import {retrieveSyntheticOffers} from '@/lib/synthetic-flights';
import {searchStarterFlights,searchStarterRoundTrip,getStarterFlightById,getStarterRouteCount,type StarterFlightCandidate,type StarterFlightSearchResult,type StarterRoundTripCombo as SearchRoundTripCombo} from '@/lib/starter-flight-search';
import {z} from 'zod';
const intent=intentSchema;
function synthetic(t:Intent){return retrieveSyntheticOffers(t)}
function makeOffers(t:Intent){return synthetic(t).offers}
function retrievalSummary(t:Intent){return synthetic(t).summary}
function hydrateSyntheticTrips(s:State){for(const trip of s.trips){const legacy=!trip.retrieval||trip.offers.some(o=>!o.source);if(legacy){const r=synthetic(trip);trip.offers=r.offers;trip.retrieval=r.summary;delete trip.aiRecommendation;}}}
async function consumeLlmQuota(owner:string){const minute=Math.floor(Date.now()/60000),day=new Date().toISOString().slice(0,10);const quota=await database().prepare(`INSERT INTO llm_limits(owner,minute,count,day,daily_count) VALUES (?,?,1,?,1)
 ON CONFLICT(owner) DO UPDATE SET minute=excluded.minute,count=CASE WHEN llm_limits.minute=excluded.minute THEN llm_limits.count+1 ELSE 1 END,day=excluded.day,daily_count=CASE WHEN llm_limits.day=excluded.day THEN llm_limits.daily_count+1 ELSE 1 END
 WHERE (llm_limits.minute!=excluded.minute OR llm_limits.count<6) AND (llm_limits.day!=excluded.day OR llm_limits.daily_count<100) RETURNING owner`).bind(owner,minute,day).first();if(!quota)throw new LlmError('LLM_USER_LIMIT','Bạn đã đạt giới hạn chat (6 lượt/phút hoặc 100 lượt/ngày). Vui lòng thử lại sau.',429);}
function ensureStarter(s:State):StarterConversation{if(!s.starter)s.starter={messages:[],draft:{},searchFilters:{},phase:'collecting',selectedOfferId:null,selectedOffer:null,selectedOutboundOffer:null,selectedReturnOffer:null,tripMode:'unspecified',dateMode:'fixed',activeLeg:'outbound',checkoutStage:'none'};s.starter.searchFilters??={};s.starter.phase??='collecting';s.starter.tripMode??='unspecified';s.starter.dateMode??='fixed';s.starter.activeLeg??='outbound';s.starter.checkoutStage??='none';if(s.starter.selectedOfferId&&!s.starter.selectedOffer){const c=getStarterFlightById(s.starter.selectedOfferId,s.starter.draft.passengers??1);if(c)s.starter.selectedOffer=selectedSnapshot(c);}if(!s.starter.selectedOutboundOffer&&s.starter.selectedOffer)s.starter.selectedOutboundOffer=s.starter.selectedOffer;return s.starter;}
function starterCandidate(s:State){const d=s.starter?.draft||{};return {...d,name:(d.name||`${d.from||'Trip'} → ${d.to||'Trip'}`).slice(0,70),budget:d.budget??100000,passengers:d.passengers??1,baggage:d.baggage??s.profile.baggage??23,transit:d.transit??24,seat:d.seat||s.profile.seat||'No preference'};}
function starterReady(s:State){return intent.safeParse(starterCandidate(s)).success;}
function normText(text:string){return text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function affirmative(text:string){
 const n=normText(text);
 // Keep this deliberately narrow. `co chuyen nao ...?` is a search question, not a yes.
 return /^(co|duoc|ok|okay|yes|yep|dong y|uh|uhm|oke)$/.test(n)
  || /^(co|duoc|ok|okay|yes|dong y) (nhe|nha|a|di|luon)$/.test(n)
  || /^(co|duoc|ok|okay|yes|dong y) (hay )?(chon|lay|cho toi|chuyen sang) (chuyen|lua chon|option|cai) (nay|do|vua recommend|vua de xuat|tot nhat)$/.test(n)
  || /^(lay|chon|cho toi|chuyen sang) (chuyen|lua chon|option|cai) (nay|do|vua recommend|vua de xuat|tot nhat)$/.test(n)
  || /^(go with|take|choose|select) (this|that|the recommended|the best) (one|option|flight)?$/.test(n);
}
function negative(text:string){const n=normText(text);return /^(khong|khong can|thoi|no|nope|cancel|bo qua)$/.test(n);}
function confirmPendingIntentText(text:string){const n=normText(text);return affirmative(text)||/^(xac nhan|ap dung|luu thay doi|luu lai|confirm|confirm update|apply|apply change|save change)$/.test(n);}
function dismissPendingIntentText(text:string){const n=normText(text);return negative(text)||/^(giu hien tai|giu nhu cu|khong ap dung|dismiss|keep current|keep it)$/.test(n);}
function removeBudgetLimitText(text:string){const n=normText(text);return /^(bo|xoa|go) (gioi han )?ngan sach$/.test(n)||/^(khong|ko) (can )?gioi han ngan sach$/.test(n)||/^(ngan sach )?(khong gioi han|thoai mai|linh hoat)$/.test(n)||/^(remove|drop|clear|no) (the )?budget( limit)?$/.test(n)||/^(no budget limit|unlimited budget)$/.test(n);}
function wantsRoundTrip(text:string){const n=normText(text);return /\b(khu hoi|round trip|roundtrip|di ve|ve lai|return ticket|return flight)\b/.test(n);}
function wantsOneWay(text:string){const n=normText(text);return /\b(mot chieu|one way|oneway|chi chieu di|chi di|khong can chieu ve|khong can khu hoi|khong can ve|no return)\b/.test(n);}
function cheapestText(text:string){const n=normText(text);return /\b(re nhat|gia re nhat|cheapest|lowest price|tiet kiem nhat)\b/.test(n);}
function windowText(text:string){const n=normText(text);return /\b(trong khoang|khoang thoi gian|between|within|tu .* den|from .* to)\b/.test(n);}
function avoidChinaTransitText(text:string){const n=normText(text);return (/\b(transit|noi chuyen|diem dung|qua)\b/.test(n)&&/\b(khong|tranh|not|avoid)\b/.test(n)&&/\b(trung quoc|china|guangzhou|shanghai|xiamen|can|pvg|xmn)\b/.test(n))||/\b(khong phai trung quoc|not china|avoid china)\b/.test(n);}
function requireTransitText(text:string){const n=normText(text);return /\b(co transit|co noi chuyen|phai transit|phai noi chuyen|with transit|one stop|1 stop)\b/.test(n);}
function shortTransitText(text:string){const n=normText(text);return /\b(transit ngan|noi chuyen ngan|it transit|short transit|short connection)\b/.test(n);}
function moreBaggageText(text:string){const n=normText(text);return /\b(nhieu hanh ly hon|them hanh ly|nhieu kg hon|nhieu can hon|tang hanh ly|more baggage|extra baggage|more checked baggage)\b/.test(n);}
function nextBaggageKg(current:number){if(current<23)return 23;if(current<32)return 32;if(current<46)return 46;return 46;}
function whatNextText(text:string){const n=normText(text);return /^(roi gio sao|gio sao|tiep theo lam gi|sau do sao|what next|now what|then what)$/.test(n);}
function declinePaymentText(text:string){const n=normText(text);return /\b(chua thanh toan|khong thanh toan|de sau|theo doi gia|monitor|not pay now|pay later|track price)\b/.test(n);}
function paymentText(text:string){const n=normText(text);return /\b(thanh toan|dat ve|checkout|pay|book now|continue booking)\b/.test(n)&&!declinePaymentText(text);}
function applyTripPendingIntent(t:Trip){const pending=t.pendingIntent;if(!pending||pending.baseVersion!==t.version)throw new Error('VALIDATION:Đề xuất đã thay đổi. Hãy tải lại chuyến đi.');const current=Object.fromEntries(Object.keys(intentSchema.innerType().shape).map(k=>[k,(t as any)[k]]));const merged=intent.parse({...current,...pending.patch});Object.assign(t,merged,{version:t.version+1,offers:makeOffers(merged),retrieval:retrievalSummary(merged)});delete t.aiRecommendation;delete t.pendingIntent;return merged;}
function applyTripPatchNow(t:Trip,patch:Partial<Intent>){
 const current=Object.fromEntries(Object.keys(intentSchema.innerType().shape).map(k=>[k,(t as any)[k]]));
 const merged=intent.parse({...current,...patch});
 const routeOrDateChanged=['from','to','start'].some(k=>k in patch);
 Object.assign(t,merged,{version:t.version+1,offers:makeOffers(merged),retrieval:retrievalSummary(merged)});
 delete t.aiRecommendation;
 delete t.pendingIntent;
 if(routeOrDateChanged&&t.selectedOffer&&(patch.from!==undefined||patch.to!==undefined||(patch.start!==undefined&&t.selectedOffer.departureDate!==merged.start)))delete t.selectedOffer;
 return merged;
}
function compactIntentUpdateReply(patch:Partial<Intent>){
 const labels:Record<string,string>={from:'điểm đi',to:'điểm đến',start:'ngày đi',end:'ngày về',budget:'ngân sách',passengers:'số khách',baggage:'hành lý',transit:'nối chuyến',seat:'ghế',name:'tên chuyến'};
 const changed=Object.keys(patch).map(k=>labels[k]||k);
 return changed.length?`Đã cập nhật Travel Intent: ${changed.join(', ')}.`:'Đã cập nhật Travel Intent.';
}
function statusQuestion(text:string){const n=normText(text);return /\b(xong chua|xong roi chua|da xong chua|da doi chua|status|done yet|is it done)\b/.test(n);}
function selectionCommand(text:string){
 const n=normText(text);
 return /\b(chon|lay|book|select|choose|take)\b.*\b(chuyen|lua chon|option|cai|recommended|recommend|de xuat|nay|do|tot nhat)\b/.test(n)
  || /\b(cho toi|chuyen sang|go with)\b.*\b(chuyen|lua chon|option|cai|recommended|recommend|de xuat|nay|do|tot nhat)\b/.test(n)
  || /^(chuyen|lua chon|option|cai) (nay|do|vua recommend|vua de xuat)$/.test(n);
}
function clearSelectionIfIntentChanged(st:StarterConversation,patch:Partial<Intent>){const out=st.selectedOutboundOffer||st.selectedOffer,ret=st.selectedReturnOffer,total=(out?.totalPriceAUD||0)+(ret?.totalPriceAUD||0);let invalid=['from','to','start','end'].some(k=>k in patch);if(patch.baggage!=null&&((out&&out.baggageKg<patch.baggage)||(ret&&ret.baggageKg<patch.baggage)))invalid=true;if(patch.transit!=null&&((out&&out.transitMinutes>patch.transit*60)||(ret&&ret.transitMinutes>patch.transit*60)))invalid=true;if(patch.budget!=null&&patch.budget<100000&&total>0&&total>patch.budget)invalid=true;if(invalid){st.selectedOfferId=null;st.selectedOffer=null;st.selectedOutboundOffer=null;st.selectedReturnOffer=null;st.pendingSuggestion=undefined;st.lastSearch=undefined;st.outboundSearch=undefined;st.returnSearch=undefined;st.roundTripCombos=undefined;st.returnSuggestionPending=false;st.checkoutStage='none';st.activeLeg='outbound';st.phase='collecting';}}
function mergeSearchFilters(st:StarterConversation,q:StarterOfferQuery):StarterSearchFilters{
 const f:{[key:string]:unknown}={...(st.searchFilters||{})};
 for(const key of q.clearFilters||[])delete f[key];
 for(const key of ['maxPrice','maxTransit','minBaggage','directOnly','requireTransit','transitVia','excludeChina'] as const){const value=q[key];if(value!==undefined&&value!==null)f[key]=value;}
 if(q.sortBy)f.sortBy=q.sortBy;if(q.limit)f.limit=q.limit;
 st.searchFilters=f as StarterSearchFilters;return st.searchFilters;
}
function currentQuery(st:StarterConversation,requested=true):StarterOfferQuery{return {requested,maxPrice:st.searchFilters?.maxPrice??null,maxTransit:st.searchFilters?.maxTransit??null,minBaggage:st.searchFilters?.minBaggage??null,directOnly:st.searchFilters?.directOnly??null,requireTransit:st.searchFilters?.requireTransit??null,transitVia:st.searchFilters?.transitVia??null,excludeChina:st.searchFilters?.excludeChina??null,sortBy:st.searchFilters?.sortBy||'best',limit:st.searchFilters?.limit||3,clearFilters:[]};}
function addIsoDays(value:string,days:number){const d=new Date(value+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function buildStarterSearch(s:State,leg:StarterLeg='outbound'):Parameters<typeof searchStarterFlights>[0]|null{const st=s.starter,d=st?.draft,f=st?.searchFilters;if(!d?.from||!d?.to)return null;const isReturn=leg==='return',useWindow=st?.dateMode==='window'&&!!d.start&&!!d.end,selectedOut=st?.selectedOutboundOffer||st?.selectedOffer;const windowStart=useWindow?(isReturn&&selectedOut?addIsoDays(selectedOut.departureDate,1):d.start!):null;return {from:isReturn?d.to:d.from,to:isReturn?d.from:d.to,departureDate:useWindow?null:(isReturn?(d.end||null):(d.start||null)),windowStart,windowEnd:useWindow?(d.end||null):null,passengers:d.passengers??1,maxPrice:f?.maxPrice??(d.budget&&d.budget<100000?d.budget:null),maxTransit:f?.maxTransit??null,minBaggage:f?.minBaggage??d.baggage??null,directOnly:f?.directOnly??null,requireTransit:f?.requireTransit??null,transitVia:f?.transitVia??null,excludeChina:f?.excludeChina??null,sortBy:f?.sortBy||'best',limit:f?.limit||3};}
function shortOffer(c:StarterFlightCandidate){const transit=c.stops===0?'bay thẳng':`${Math.round(c.transitMinutes/6)/10}h transit tại ${c.transitCity||c.transitAirport}`;return `**${c.id}** (${c.departureDate}) — AUD ${c.totalPriceAUD.toLocaleString()} · ${c.totalDurationText} · ${transit} · ${c.baggageKg}kg`;}
function selectedSnapshot(c:StarterFlightCandidate):StarterSelectedOffer{return {offerId:c.id,departureDate:c.departureDate,departureTime:c.departureTime,arrivalDate:c.arrivalDate,arrivalTime:c.arrivalTime,routing:c.routing,totalPriceAUD:c.totalPriceAUD,totalDurationText:c.totalDurationText,stops:c.stops,transitAirport:c.transitAirport,transitCity:c.transitCity,transitMinutes:c.transitMinutes,baggageKg:c.baggageKg,flightReference:c.flightReference,fareType:c.fareType,flexibility:c.flexibility,selectedAt:new Date().toISOString()};}
function fallbackSearchReply(result:StarterFlightSearchResult){
 if(result.routeRows===0)return 'Dataset demo hiện chưa có record cho route này, nên mình không thể tạo một chuyến giả. Bạn có thể thử route khác có trong dữ liệu.';
 if(result.exactMatches.length){const lines=result.exactMatches.slice(0,3).map((o,i)=>`${i+1}. ${shortOffer(o)}`).join('\n');return `Mình đã tìm xong. Lựa chọn phù hợp nhất theo các điều kiện hiện tại là ${shortOffer(result.exactMatches[0])}.\n\nTop lựa chọn:\n${lines}\n\nĐây là dữ liệu giả lập của prototype, không phải giá/tồn chỗ live của Vietnam Airlines.`;}
 if(result.nearbyMatches.length){const lines=result.nearbyMatches.slice(0,3).map((o,i)=>`${i+1}. ${shortOffer(o)}`).join('\n');return `Không có lựa chọn thỏa toàn bộ điều kiện vào đúng ngày ${result.requestedDate}. Ngày gần đó có:\n\n${lines}\n\nMình đề xuất lựa chọn đầu tiên. Bạn có muốn chuyển ngày đi sang ${result.nearbyMatches[0].departureDate} và chọn chuyến đó không?\n\nĐây là dữ liệu giả lập của prototype.`;}
 if(result.sameDateNearMisses.length){const n=result.sameDateNearMisses[0];return `Không có chuyến thỏa toàn bộ điều kiện vào đúng ngày ${result.requestedDate}. Lựa chọn gần nhất là ${shortOffer(n)}.\nKhông đạt vì: ${n.violations.join(' ')}\nCó thể nới nhỏ nhất bằng cách: ${n.relaxations.join(' ')}\n\nĐây là dữ liệu giả lập của prototype.`;}
 return `Dataset demo có route này nhưng không có record phù hợp với ngày/bộ lọc hiện tại. Mình sẽ không tự bịa chuyến bay. ${result.requestedDate?'Bạn có thể đổi ngày hoặc nới một điều kiện.':''}`;
}
function saveLastSearch(st:StarterConversation,text:string,result:StarterFlightSearchResult,leg:StarterLeg='outbound'){
 const visible=result.exactMatches.length?result.exactMatches:result.nearbyMatches.length?result.nearbyMatches:result.sameDateNearMisses;
 const saved={query:text,leg,requestedDate:result.requestedDate,exactMatchIds:result.exactMatches.map(x=>x.id),nearbyMatchIds:result.nearbyMatches.map(x=>x.id),nearMissIds:result.sameDateNearMisses.map(x=>x.id),recommendedOfferId:result.recommended?.id||null,offers:visible.slice(0,3).map(selectedSnapshot),filters:{...(st.searchFilters||{})},searchedAt:new Date().toISOString()};
 st.lastSearch=saved;if(leg==='outbound')st.outboundSearch=saved;else st.returnSearch=saved;
 st.activeLeg=leg;st.roundTripCombos=undefined;
 if(result.nearbyMatches.length){const best=result.recommended||result.nearbyMatches[0];st.pendingSuggestion={kind:'switch_departure',offerId:best.id,departureDate:best.departureDate,reason:'No exact-date match; nearest suitable alternative.',filters:{...(st.searchFilters||{})},created:new Date().toISOString()};st.phase='awaiting-confirmation';}
 else {st.pendingSuggestion=undefined;st.phase='searching';}
}
function selectedReply(st:StarterConversation){
 const out=st.selectedOutboundOffer||st.selectedOffer,ret=st.selectedReturnOffer;
 if(!out)return 'Bạn chưa chọn chuyến nào. Mình có thể tìm và xếp hạng các lựa chọn trước.';
 if(ret)return `Bạn đã chọn combo khứ hồi ${out.offerId} + ${ret.offerId}. Tiếp theo LIA ưu tiên hoàn tất thông tin hành khách và chuyển sang thanh toán.`;
 if(st.returnSuggestionPending)return `Bạn đã chọn chiều đi ${out.offerId}. Mình có thể tìm thêm chiều về để tạo combo khứ hồi, hoặc bạn có thể giữ hành trình một chiều.`;
 return `Bạn đang chọn ${out.offerId}. Tiếp theo là thông tin hành khách và thanh toán; nếu chưa muốn thanh toán, bạn có thể chuyển sang theo dõi giá.`;
}
function statusReply(st:StarterConversation){if(st.pendingSuggestion){const c=getStarterFlightById(st.pendingSuggestion.offerId,st.draft.passengers??1);return `Mình đã tìm xong và đang chờ xác nhận đổi ngày${c?` cho ${c.id}`:''}.`; }if(st.selectedReturnOffer)return 'Đã chọn đủ hai chiều. Bước tiếp theo là thông tin hành khách và thanh toán.';if(st.selectedOutboundOffer||st.selectedOffer)return st.returnSuggestionPending?'Đã chọn chiều đi. Bạn có thể thêm chiều về hoặc tiếp tục một chiều.':'Đã chọn chuyến. Bước tiếp theo là checkout; theo dõi giá chỉ dùng nếu bạn chưa muốn thanh toán.';if(st.lastSearch?.recommendedOfferId)return 'Mình đã tìm xong nhưng bạn chưa chọn phương án nào.';return 'Chưa có tìm kiếm hoàn chỉnh. Bạn hãy cho mình tuyến/ngày và yêu cầu tìm chuyến.';}
function reverseLegNote(st:StarterConversation){const from=st.draft.to,to=st.draft.from;if(!from||!to||!st.draft.end)return '';const count=getStarterRouteCount(from,to);return count>0?` Dataset có ${count} record cho chặng về ${from} → ${to}.`:` Dataset demo hiện chưa có record ${from} → ${to}.`;}
function markCheckoutReady(s:State,st:StarterConversation){st.checkoutStage='offer-payment';st.returnSuggestionPending=false;st.phase='selected';st.lastSearch=undefined;st.outboundSearch=undefined;st.returnSearch=undefined;st.roundTripCombos=undefined;const out=st.selectedOutboundOffer||st.selectedOffer,ret=st.selectedReturnOffer,total=(out?.totalPriceAUD||0)+(ret?.totalPriceAUD||0);if(!out)return;const text=ret?`Hành trình khứ hồi đã chọn · ${out.offerId} + ${ret.offerId} · tổng demo AUD ${total.toLocaleString()}. Mở LIA để hoàn tất thông tin hành khách và tiếp tục thanh toán.`:`Chuyến ${out.offerId} đã chọn · demo AUD ${total.toLocaleString()}. Mở LIA để hoàn tất thông tin hành khách và tiếp tục thanh toán.`;const existing=s.notifications.find(n=>n.tripId==='starter'&&!n.read);if(existing)existing.text=text;else if(s.profile.notifications)s.notifications.unshift({id:crypto.randomUUID(),tripId:'starter',text,read:false});}
function acceptSuggestion(st:StarterConversation){
 const p=st.pendingSuggestion;if(!p)return null;const c=getStarterFlightById(p.offerId,st.draft.passengers??1);if(!c)return null;
 const leg=st.activeLeg||'outbound';if(p.kind==='switch_departure'){if(leg==='return')st.draft.end=p.departureDate;else st.draft.start=p.departureDate;}
 if(leg==='return')st.selectedReturnOffer=selectedSnapshot(c);else {st.selectedOutboundOffer=selectedSnapshot(c);st.selectedOffer=st.selectedOutboundOffer;st.selectedOfferId=c.id;}
 st.searchFilters={...p.filters};st.pendingSuggestion=undefined;st.phase='selected';
 return p.kind==='switch_departure'?`Đã chọn phương án gần nhất và cập nhật ngày ${leg==='return'?'về':'đi'} sang ${p.departureDate}.`:'Đã chọn chuyến này.';
}
function selectRecommended(st:StarterConversation){const id=st.lastSearch?.recommendedOfferId;if(!id)return null;const c=getStarterFlightById(id,st.draft.passengers??1);if(!c)return null;const leg=st.activeLeg||'outbound';if(st.lastSearch?.nearbyMatchIds.includes(id)){st.pendingSuggestion={kind:'switch_departure',offerId:id,departureDate:c.departureDate,reason:'Recommended nearby-date option.',filters:{...(st.searchFilters||{})},created:new Date().toISOString()};return acceptSuggestion(st);}if(leg==='return')st.selectedReturnOffer=selectedSnapshot(c);else {st.selectedOutboundOffer=selectedSnapshot(c);st.selectedOffer=st.selectedOutboundOffer;st.selectedOfferId=id;}st.phase='selected';return leg==='return'?'Đã chọn chuyến về được đề xuất.':'Đã chọn chuyến đi được đề xuất.';}
function compactStarterSearchReply(result:StarterFlightSearchResult,leg:StarterLeg='outbound'){
 const label=leg==='return'?'chuyến về':'chuyến đi';
 if(result.routeRows===0)return `Mình chưa có dữ liệu demo cho ${label} trên tuyến này.`;
 if(result.exactMatches.length)return `Mình tìm thấy ${Math.min(result.exactMatches.length,3)} ${label} phù hợp. Chọn trực tiếp trên thẻ.`;
 if(result.nearbyMatches.length)return `Không có ${label} khớp đúng ngày ${result.requestedDate||''}. Mình đã đưa các lựa chọn gần nhất vào thẻ.`;
 if(result.sameDateNearMisses.length)return `Chưa có ${label} khớp toàn bộ điều kiện. Mình đã hiển thị lựa chọn gần nhất để bạn cân nhắc.`;
 return `Chưa có ${label} phù hợp với các điều kiện hiện tại. Hãy đổi ngày hoặc nới một điều kiện.`;
}
async function runStarterSearch(s:State,text:string,q:StarterOfferQuery,leg:StarterLeg='outbound'){const st=ensureStarter(s);mergeSearchFilters(st,q);const filters=buildStarterSearch(s,leg);if(!filters)return {reply:'Mình cần điểm đi và điểm đến trước khi tìm chuyến.',result:null};st.phase='searching';const result=searchStarterFlights(filters);saveLastSearch(st,text,result,leg);return {reply:compactStarterSearchReply(result,leg),result};}
function comboSnapshot(c:SearchRoundTripCombo):StarterRoundTripCombo{return {id:c.id,outbound:selectedSnapshot(c.outbound),return:selectedSnapshot(c.return),totalPriceAUD:c.totalPriceAUD,totalDurationMinutes:c.totalDurationMinutes,totalTransitMinutes:c.totalTransitMinutes,rankingScore:c.rankingScore};}
function runRoundTripSearch(s:State,text:string,q:StarterOfferQuery){const st=ensureStarter(s),d=st.draft;if(!d.from||!d.to||!d.start||!d.end)return {reply:'Mình cần tuyến và hai mốc ngày để ghép combo khứ hồi.',result:null};mergeSearchFilters(st,q);const f=st.searchFilters||{};const result=searchStarterRoundTrip({from:d.from,to:d.to,startDate:d.start,endDate:d.end,dateMode:st.dateMode||'fixed',passengers:d.passengers??1,filters:{maxPrice:f.maxPrice??(d.budget&&d.budget<100000?d.budget:null),maxTransit:f.maxTransit??null,minBaggage:f.minBaggage??d.baggage??null,directOnly:f.directOnly??null,requireTransit:f.requireTransit??null,transitVia:f.transitVia??null,excludeChina:f.excludeChina??null,sortBy:f.sortBy||'best',limit:f.limit||3},limit:f.limit||3});st.tripMode='round-trip';st.activeLeg='outbound';st.pendingSuggestion=undefined;st.lastSearch=undefined;st.outboundSearch=undefined;st.returnSearch=undefined;st.roundTripCombos=result.combos.map(comboSnapshot);st.phase='searching';if(result.combos.length)return {reply:`Mình đã ghép ${result.combos.length} combo khứ hồi phù hợp từ dataset. Chọn combo trực tiếp trên thẻ.`,result};if(!result.routeRowsReturn)return {reply:`Mình có dữ liệu chiều đi nhưng chưa có dữ liệu demo cho chiều về ${d.to} → ${d.from}.`,result};return {reply:'Chưa có combo khứ hồi thỏa toàn bộ điều kiện. Hãy nới ngân sách, hành lý, transit hoặc khoảng ngày.',result};}
function createTripFromStarter(s:State,status='draft'){if(!s.starter)throw new Error('VALIDATION:Start a conversation with LIA first.');const parsed=intent.safeParse(starterCandidate(s));if(!parsed.success)throw new Error('VALIDATION:LIA still needs a valid route and travel window.');const data=parsed.data,st=s.starter,out=st.selectedOutboundOffer||st.selectedOffer,ret=st.selectedReturnOffer;const trip:Trip={...data,id:crypto.randomUUID(),version:1,status,selectedOffer:out||null,selectedReturnOffer:ret||null,searchFilters:{...(st.searchFilters||{})},offers:makeOffers(data),retrieval:retrievalSummary(data),history:[],messages:[...st.messages,{role:'assistant',text:status==='monitoring'?'Bạn chưa thanh toán nên LIA đã chuyển hành trình sang theo dõi giá demo.':'Hành trình đã sẵn sàng cho bước đặt vé trực tiếp.'}]};s.trips.unshift(trip);for(const n of s.notifications)if(n.tripId==='starter')n.tripId=trip.id;delete s.starter;return trip;}
async function load(id:string,profileName:string){const db=database();await db.prepare('INSERT OR IGNORE INTO workspaces (owner,payload,revision) VALUES (?,?,0)').bind(id,JSON.stringify(initialState(profileName))).run();return (await db.prepare('SELECT payload,revision FROM workspaces WHERE owner=?').bind(id).first()) as {payload:string;revision:number};}
export async function GET(r:Request){try{const identity=await authIdentity(r),row=await load(identity.owner,identity.name),state=JSON.parse(row.payload) as State;hydrateSyntheticTrips(state);return Response.json({state,revision:row.revision,llm:llmStatus(),auth:{kind:identity.kind,name:identity.name,email:identity.email,phone:identity.phone}},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(r:Request){try{mutationGuard(r);const identity=await authIdentity(r),id=identity.owner,b=z.object({action:z.string(),revision:z.number().int(),tripId:z.string().nullable().optional()}).passthrough().parse(await r.json()),row=await load(id,identity.name),s:State=JSON.parse(row.payload);hydrateSyntheticTrips(s);if(typeof s.profile.family!=='boolean')s.profile.family=false;if(b.revision!==row.revision)return Response.json({error:'This trip changed in another tab. Refresh and try again.'},{status:409});let result:any=null;if(!Array.isArray(s.preferenceEvidence))s.preferenceEvidence=[];const t=s.trips.find(x=>x.id===b.tripId);
if(b.action==='create'||b.action==='edit'){const parsed=intent.safeParse(b.intent);if(!parsed.success)throw new Error('VALIDATION:Please check the trip fields, airports and dates.');const data=parsed.data;if(b.action==='edit'){if(!t)throw new Error('VALIDATION:Trip not found.');Object.assign(t,data,{version:t.version+1,offers:makeOffers(data),retrieval:retrievalSummary(data)});delete t.aiRecommendation;delete t.pendingIntent;}else {const trip:Trip={...data,id:crypto.randomUUID(),version:1,status:'draft',offers:makeOffers(data),retrieval:retrievalSummary(data),history:[],messages:[{role:'assistant',text:'I have prepared your travel intent. Review your requirements, then start monitoring. These options were retrieved from a synthetic demo dataset. Live Vietnam Airlines search is not connected.'}]};s.trips.unshift(trip);result={tripId:trip.id};}}
else if(b.action==='starter_chat'){
 const text=z.string().trim().min(1).max(2000).parse(b.text),st=ensureStarter(s);if(!llmStatus().configured)throw new LlmError('LLM_NOT_CONFIGURED','Chat AI chưa được kết nối với OpenAI. Hãy kiểm tra OPENAI_API_KEY và Billing.');
 let reply='',action:StarterDialogueAction='other',offerQuery:StarterOfferQuery=currentQuery(st,false),finalizeStatus:null|'draft'|'monitoring'=null;
 const hasSelected=!!(st.selectedOutboundOffer||st.selectedOffer),hasCompleteSelection=hasSelected&&(st.tripMode!=='round-trip'||!!st.selectedReturnOffer);
 if(st.pendingSuggestion&&affirmative(text)){action='accept_suggestion';reply=acceptSuggestion(st)||'';}
 else if(st.pendingSuggestion&&negative(text)){action='reject_suggestion';st.pendingSuggestion=undefined;st.phase='searching';reply='Được, mình giữ nguyên ngày hiện tại. Bạn có thể đổi điều kiện hoặc yêu cầu tìm lại.';}
 else if(st.returnSuggestionPending&&affirmative(text)){action='search';st.tripMode='round-trip';st.returnSuggestionPending=false;st.activeLeg='return';const search=await runStarterSearch(s,text,currentQuery(st,true),'return');reply=`Được. ${search.reply}`;result={search:search.result};}
 else if(st.returnSuggestionPending&&(negative(text)||wantsOneWay(text))){action='other';st.tripMode='one-way';st.returnSuggestionPending=false;st.selectedReturnOffer=null;markCheckoutReady(s,st);reply='Được, giữ hành trình một chiều. Tiếp theo là thông tin hành khách và thanh toán.';}
 else if(statusQuestion(text)){action='check_status';reply=statusReply(st);}
 else if(whatNextText(text)&&hasSelected){action='explain_selected';reply=selectedReply(st);}
 else if(declinePaymentText(text)&&st.checkoutStage==='offer-payment'&&hasCompleteSelection){action='other';reply='Được. Mình sẽ chưa chuyển sang thanh toán và đưa hành trình này vào theo dõi giá demo.';finalizeStatus='monitoring';}
 else if(paymentText(text)&&st.checkoutStage==='offer-payment'&&hasCompleteSelection){action='other';reply='Hành trình đã chốt. Nếu hồ sơ hành khách đã đủ, nút Thanh toán (demo) sẽ hiện bên dưới; nếu chưa, hãy điền thông tin hành khách trước.';}
 else if(avoidChinaTransitText(text)){
  action='search';offerQuery={...currentQuery(st,true),requested:true,requireTransit:true,excludeChina:true,directOnly:null,transitVia:null,clearFilters:['directOnly','transitVia']};
  mergeSearchFilters(st,offerQuery);
  if(st.tripMode==='round-trip'&&!st.selectedOutboundOffer&&!st.selectedOffer&&st.draft.start&&st.draft.end){const search=runRoundTripSearch(s,text,offerQuery);reply=search.reply;result={search:search.result};}
  else {const leg=st.activeLeg||'outbound',search=await runStarterSearch(s,text,offerQuery,leg);reply=search.reply;result={search:search.result};}
 }
 else if(moreBaggageText(text)){
  action='search';const current=Number(st.draft.baggage??s.profile.baggage??23),next=nextBaggageKg(current);clearSelectionIfIntentChanged(st,{baggage:next});st.draft={...st.draft,baggage:next};offerQuery={...currentQuery(st,true),requested:true,minBaggage:next,clearFilters:[]};
  if(next===current&&current>=46)reply='Dataset demo hiện hỗ trợ tối đa 46 kg/người. Mình sẽ giữ mức này và tìm lại.';
  const leg=st.activeLeg||'outbound';if(st.tripMode==='round-trip'&&!st.selectedOutboundOffer&&!st.selectedOffer&&st.draft.start&&st.draft.end){const search=runRoundTripSearch(s,text,offerQuery);reply=reply||search.reply;result={search:search.result};}else{const search=await runStarterSearch(s,text,offerQuery,leg);reply=reply||`Đã tăng yêu cầu hành lý lên ${next} kg/người. ${search.reply}`;result={search:search.result};}
 }
 else if((wantsRoundTrip(text)||((st.dateMode==='window'||windowText(text))&&cheapestText(text)))&&cheapestText(text)&&st.draft.from&&st.draft.to&&st.draft.start&&st.draft.end&&getStarterRouteCount(st.draft.to,st.draft.from)>0&&!wantsOneWay(text)){
  action='search';st.tripMode='round-trip';if(windowText(text)||st.dateMode==='window')st.dateMode='window';offerQuery={...currentQuery(st,true),requested:true,sortBy:'price',clearFilters:[]};const search=runRoundTripSearch(s,text,offerQuery);reply=search.reply;result={search:search.result};
 }
 else if(selectionCommand(text)&&st.pendingSuggestion){action='accept_suggestion';reply=acceptSuggestion(st)||statusReply(st);}
 else if(selectionCommand(text)&&st.lastSearch?.recommendedOfferId){action='select_recommended';reply=selectRecommended(st)||statusReply(st);}
 else {
  await consumeLlmQuota(id);const answer=await startChatWithLlm(st.draft,st.messages,text,s.profile,st);action=answer.action;offerQuery=answer.offerQuery;clearSelectionIfIntentChanged(st,answer.patch);st.draft={...st.draft,...answer.patch};
  const explicitRound=wantsRoundTrip(text),explicitOne=wantsOneWay(text),cheap=cheapestText(text),window=windowText(text),fixedRound=/\b(di|khoi hanh).*\b(ve|return)\b/.test(normText(text));
  if(window&&!fixedRound)st.dateMode='window';if(explicitRound){st.tripMode='round-trip';st.dateMode=(window&&!fixedRound)?'window':st.dateMode||'fixed';st.returnSuggestionPending=false;}
  if(explicitOne){st.tripMode='one-way';st.dateMode='fixed';st.selectedReturnOffer=null;st.returnSuggestionPending=false;}
  if(cheap){offerQuery={...offerQuery,requested:true,sortBy:'price'};}
  if(requireTransitText(text)){offerQuery={...offerQuery,requested:true,requireTransit:true,directOnly:null,clearFilters:[...(offerQuery.clearFilters||[]),'directOnly']};}
  if(avoidChinaTransitText(text)){offerQuery={...offerQuery,requested:true,requireTransit:true,excludeChina:true,directOnly:null,transitVia:null,clearFilters:[...(offerQuery.clearFilters||[]),'directOnly','transitVia']};}
  if(shortTransitText(text)){offerQuery={...offerQuery,requested:true,sortBy:'transit'};}
  if(moreBaggageText(text)&&answer.patch.baggage===undefined){const next=nextBaggageKg(Number(st.draft.baggage??s.profile.baggage??23));st.draft={...st.draft,baggage:next};offerQuery={...offerQuery,requested:true,minBaggage:next};}
  const reverseAvailable=!!(st.draft.from&&st.draft.to&&getStarterRouteCount(st.draft.to,st.draft.from)>0);
  if(!explicitOne&&cheap&&st.draft.start&&st.draft.end&&reverseAvailable&&(explicitRound||window||st.tripMode==='unspecified')){st.tripMode='round-trip';st.dateMode=explicitRound&&!window?'fixed':'window';}
  if(action==='accept_suggestion'&&st.pendingSuggestion)reply=acceptSuggestion(st)||answer.reply;
  else if(action==='reject_suggestion'&&st.pendingSuggestion){st.pendingSuggestion=undefined;st.phase='searching';reply='Được, mình không áp dụng đề xuất đó. Bạn có thể yêu cầu tìm phương án khác.';}
  else if(action==='check_status')reply=statusReply(st);
  else if(action==='select_recommended')reply=selectRecommended(st)||answer.reply;
  else if(action==='explain_selected')reply=selectedReply(st);
  else if(action==='search'||action==='compare'||offerQuery.requested){
   if(st.tripMode==='round-trip'&&st.draft.start&&st.draft.end&&!st.selectedOutboundOffer&&!st.selectedOffer){const search=runRoundTripSearch(s,text,offerQuery);reply=search.reply;result={...(result||{}),search:search.result};}
   else {const leg=st.activeLeg||'outbound',search=await runStarterSearch(s,text,offerQuery,leg);reply=search.reply;result={...(result||{}),search:search.result};}
  } else reply=answer.reply;
 }
 st.messages.push({role:'user',text},{role:'assistant',text:reply});st.messages=st.messages.slice(-40);
 if(finalizeStatus){const trip=createTripFromStarter(s,finalizeStatus);result={tripId:trip.id,checkout:finalizeStatus==='draft',monitoring:finalizeStatus==='monitoring'};}
 else result={...(result||{}),ready:starterReady(s),draft:st.draft,action,offerQuery,dialogue:{phase:st.phase,tripMode:st.tripMode,dateMode:st.dateMode,activeLeg:st.activeLeg,pendingSuggestion:st.pendingSuggestion||null,selectedOfferId:st.selectedOfferId||null,selectedOffer:st.selectedOffer||null,selectedOutboundOffer:st.selectedOutboundOffer||null,selectedReturnOffer:st.selectedReturnOffer||null,returnSuggestionPending:!!st.returnSuggestionPending,checkoutStage:st.checkoutStage||'none',roundTripCombos:st.roundTripCombos||[],searchFilters:st.searchFilters||{},lastSearch:st.lastSearch||null}};
}
else if(b.action==='starter_select_offer'){
 const st=ensureStarter(s),offerId=z.string().trim().min(1).max(120).parse(b.offerId),leg:StarterLeg=b.leg==='return'?'return':(b.leg==='outbound'?'outbound':st.activeLeg||'outbound'),search=(leg==='return'?st.returnSearch:st.outboundSearch)||st.lastSearch;
 const allowed=new Set([...(search?.exactMatchIds||[]),...(search?.nearbyMatchIds||[]),...(search?.nearMissIds||[])]);if(!allowed.has(offerId))throw new Error('VALIDATION:Chuyến này không nằm trong kết quả tìm kiếm gần nhất.');const c=getStarterFlightById(offerId,st.draft.passengers??1);if(!c)throw new Error('VALIDATION:Không tìm thấy chuyến trong dataset demo.');
 if(search?.nearbyMatchIds.includes(offerId)){if(leg==='return')st.draft.end=c.departureDate;else st.draft.start=c.departureDate;}
 const snap=selectedSnapshot(c);st.pendingSuggestion=undefined;st.roundTripCombos=undefined;
 if(leg==='return'){
  st.selectedReturnOffer=snap;st.activeLeg='return';markCheckoutReady(s,st);const reply='Đã chọn chiều về. Hành trình khứ hồi đã sẵn sàng cho bước thông tin hành khách và thanh toán.';st.messages.push({role:'user',text:`Chọn chuyến về ${offerId}`},{role:'assistant',text:reply});result={selectedReturnOffer:snap,checkoutStage:st.checkoutStage,draft:st.draft};
 } else {
  st.selectedOutboundOffer=snap;st.selectedOffer=snap;st.selectedOfferId=offerId;st.activeLeg='outbound';st.phase='selected';
  let reply='Đã chọn chiều đi.';
  const reverseAvailable=!!(st.draft.to&&st.draft.from&&getStarterRouteCount(st.draft.to,st.draft.from)>0);
  if(st.tripMode==='round-trip'&&st.draft.end&&reverseAvailable){st.activeLeg='return';const q=currentQuery(st,true),searchResult=await runStarterSearch(s,'Tìm chiều về sau khi đã chọn chiều đi',q,'return');reply=`Đã chọn chiều đi. ${searchResult.reply}`;result={selectedOutboundOffer:snap,search:searchResult.result,draft:st.draft};}
  else if(st.tripMode!=='one-way'&&st.draft.end&&reverseAvailable){st.returnSuggestionPending=true;st.checkoutStage='none';st.lastSearch=undefined;st.outboundSearch=undefined;reply='Đã chọn chiều đi. Bạn có muốn thêm chiều về để tạo combo khứ hồi không?';result={selectedOutboundOffer:snap,returnSuggestionPending:true,draft:st.draft};}
  else {st.tripMode='one-way';markCheckoutReady(s,st);reply='Đã chọn chuyến một chiều. Tiếp theo là thông tin hành khách và thanh toán.';result={selectedOutboundOffer:snap,checkoutStage:st.checkoutStage,draft:st.draft};}
  st.messages.push({role:'user',text:`Chọn ${offerId}`},{role:'assistant',text:reply});
 }
 st.messages=st.messages.slice(-40);
}
else if(b.action==='starter_select_combo'){
 const st=ensureStarter(s),comboId=z.string().trim().min(1).max(260).parse(b.comboId),combo=st.roundTripCombos?.find(c=>c.id===comboId);if(!combo)throw new Error('VALIDATION:Combo này không nằm trong kết quả khứ hồi gần nhất.');st.tripMode='round-trip';st.dateMode=st.dateMode||'window';st.selectedOutboundOffer=combo.outbound;st.selectedOffer=combo.outbound;st.selectedOfferId=combo.outbound.offerId;st.selectedReturnOffer=combo.return;st.draft.start=combo.outbound.departureDate;st.draft.end=combo.return.departureDate;st.roundTripCombos=undefined;st.pendingSuggestion=undefined;markCheckoutReady(s,st);const reply=`Đã chọn combo khứ hồi. Tổng giá demo ${combo.totalPriceAUD.toLocaleString('en-AU')} AUD. Tiếp theo là thông tin hành khách và thanh toán.`;st.messages.push({role:'user',text:'Chọn combo khứ hồi này'},{role:'assistant',text:reply});st.messages=st.messages.slice(-40);result={combo,checkoutStage:st.checkoutStage,draft:st.draft};
}
else if(b.action==='starter_find_return'){
 const st=ensureStarter(s);if(!(st.selectedOutboundOffer||st.selectedOffer))throw new Error('VALIDATION:Hãy chọn chiều đi trước.');if(!st.draft.end)throw new Error('VALIDATION:Cần ngày hoặc mốc cuối cho chiều về.');st.tripMode='round-trip';st.returnSuggestionPending=false;st.activeLeg='return';const search=await runStarterSearch(s,'Tìm chiều về',currentQuery(st,true),'return');const reply=search.reply;st.messages.push({role:'user',text:'Thêm chiều về'},{role:'assistant',text:reply});st.messages=st.messages.slice(-40);result={search:search.result,draft:st.draft};
}
else if(b.action==='starter_one_way'){
 const st=ensureStarter(s);if(!(st.selectedOutboundOffer||st.selectedOffer))throw new Error('VALIDATION:Hãy chọn chuyến trước.');st.tripMode='one-way';st.selectedReturnOffer=null;st.returnSuggestionPending=false;markCheckoutReady(s,st);const reply='Được, giữ hành trình một chiều. Tiếp theo là thông tin hành khách và thanh toán.';st.messages.push({role:'user',text:'Chỉ đi một chiều'},{role:'assistant',text:reply});st.messages=st.messages.slice(-40);result={checkoutStage:st.checkoutStage,draft:st.draft};
}
else if(b.action==='starter_checkout'){
 const st=ensureStarter(s),out=st.selectedOutboundOffer||st.selectedOffer;if(!out)throw new Error('VALIDATION:Hãy chọn chuyến trước khi tiếp tục.');if(st.tripMode==='round-trip'&&!st.selectedReturnOffer)throw new Error('VALIDATION:Hãy chọn đủ chiều đi và chiều về.');const trip=createTripFromStarter(s,'draft');result={tripId:trip.id,checkout:true};
}
else if(b.action==='starter_monitor_selected'){
 const st=ensureStarter(s),out=st.selectedOutboundOffer||st.selectedOffer;if(!out)throw new Error('VALIDATION:Hãy chọn chuyến trước khi theo dõi.');if(st.tripMode==='round-trip'&&!st.selectedReturnOffer)throw new Error('VALIDATION:Hãy chọn đủ hành trình hoặc chuyển sang một chiều trước.');markCheckoutReady(s,st);const trip=createTripFromStarter(s,'monitoring');if(s.profile.notifications)s.notifications.unshift({id:crypto.randomUUID(),tripId:trip.id,text:`Đã bật theo dõi giá demo cho ${trip.from} → ${trip.to}. Prototype chỉ cập nhật khi bạn chạy kiểm tra mẫu.`,read:false});result={tripId:trip.id,monitoring:true};
}
else if(b.action==='starter_reset'){delete s.starter;result={reset:true};}
else if(b.action==='starter_confirm'){
 const st=ensureStarter(s),out=st.selectedOutboundOffer||st.selectedOffer;if(out){if(st.tripMode==='round-trip'&&!st.selectedReturnOffer)throw new Error('VALIDATION:Hãy chọn chiều về hoặc chuyển sang một chiều trước.');const trip=createTripFromStarter(s,'draft');result={tripId:trip.id};}else{const parsed=intent.safeParse(starterCandidate(s));if(!parsed.success)throw new Error('VALIDATION:LIA vẫn cần tuyến và khoảng ngày hợp lệ.');const data=parsed.data,trip:Trip={...data,id:crypto.randomUUID(),version:1,status:'draft',offers:makeOffers(data),retrieval:retrievalSummary(data),history:[],messages:[...st.messages,{role:'assistant',text:'Đã tạo Travel Intent.'}]};s.trips.unshift(trip);delete s.starter;result={tripId:trip.id};}
}
else if(b.action==='profile'){s.profile={...s.profile,...z.object({name:z.string().trim().min(1).max(60).optional(),member:z.boolean(),personalize:z.boolean(),notifications:z.boolean(),seat:z.enum(['Aisle','Window','No preference']),baggage:z.number().min(0).max(46),family:z.boolean()}).parse(b.profile)};}
else if(b.action==='read'){s.notifications.forEach(n=>n.read=true);}
else {if(!t)throw new Error('VALIDATION:Trip not found.');
if(b.action==='ai_recommend'){if(!llmStatus().configured)throw new LlmError('LLM_NOT_CONFIGURED','Chat AI chưa được kết nối với OpenAI.');await consumeLlmQuota(id);t.aiRecommendation=await recommendSyntheticOffers(t,s.profile,s.preferenceEvidence);result=t.aiRecommendation;}
else if(b.action==='preference_feedback'){const parsed=z.object({offerId:z.string().min(1),dimension:z.enum(['price','transit','journey_time','baggage','miles'])}).parse(b);const offer=t.offers.find(o=>o.id===parsed.offerId);if(!offer)throw new Error('VALIDATION:Offer not found.');s.preferenceEvidence=s.preferenceEvidence.filter(e=>!(e.tripId===t.id&&e.offerId===offer.id));s.preferenceEvidence.push({id:crypto.randomUUID(),tripId:t.id,offerId:offer.id,dimension:parsed.dimension as PreferenceDimension,created:new Date().toISOString()});s.preferenceEvidence=s.preferenceEvidence.slice(-100);delete t.aiRecommendation;result={saved:true};}
else if(b.action==='status'){if(!['monitoring','paused','cancelled'].includes(String(b.status)))throw new Error('VALIDATION:Invalid status.');t.status=String(b.status);}
else if(b.action==='delete'){s.trips=s.trips.filter(x=>x.id!==t.id);s.notifications=s.notifications.filter(x=>x.tripId!==t.id);s.bookings=s.bookings.filter(x=>x.tripId!==t.id);s.preferenceEvidence=s.preferenceEvidence.filter(x=>x.tripId!==t.id);}
else if(b.action==='chat'){
 const text=z.string().trim().min(1).max(2000).parse(b.text);
 if(removeBudgetLimitText(text)){t.messages.push({role:'user',text});if(t.budget>=100000){delete t.pendingIntent;t.messages.push({role:'assistant',text:'Travel Intent hiện đã không có giới hạn ngân sách.'});result={budgetAlreadyUnlimited:true};}else{applyTripPatchNow(t,{budget:100000});t.messages.push({role:'assistant',text:'Đã bỏ giới hạn ngân sách khỏi Travel Intent.'});result={intentUpdated:true,patch:{budget:100000}};}t.feedback=text;t.messages=t.messages.slice(-100);}
 else if(moreBaggageText(text)){const next=nextBaggageKg(t.baggage);t.messages.push({role:'user',text});if(next===t.baggage){t.messages.push({role:'assistant',text:'Travel Intent đã ở mức hành lý demo tối đa 46 kg/người.'});result={intentUpdated:false};}else{applyTripPatchNow(t,{baggage:next});t.messages.push({role:'assistant',text:`Đã tăng hành lý lên ${next} kg/người và cập nhật các lựa chọn.`});result={intentUpdated:true,patch:{baggage:next}};}t.feedback=text;t.messages=t.messages.slice(-100);}
 else {if(!llmStatus().configured)throw new LlmError('LLM_NOT_CONFIGURED','Chat AI chưa được kết nối với OpenAI. Hãy kiểm tra OPENAI_API_KEY và Billing.');await consumeLlmQuota(id);const answer=await chatWithLlm(t,text,s.profile,s.preferenceEvidence);let reply=answer.reply;delete t.pendingIntent;if(Object.keys(answer.patch).length){applyTripPatchNow(t,answer.patch);reply=compactIntentUpdateReply(answer.patch);result={intentUpdated:true,patch:answer.patch};}t.messages.push({role:'user',text},{role:'assistant',text:reply});t.feedback=text;t.messages=t.messages.slice(-100);}
}
else if(b.action==='confirm_intent'){
 const pending=t.pendingIntent;if(!pending||b.proposalId!==pending.id)throw new Error('VALIDATION:Đề xuất đã thay đổi. Hãy tải lại chuyến đi.');applyTripPendingIntent(t);t.messages.push({role:'assistant',text:'Đã áp dụng thay đổi vào Travel Intent. Bạn có thể tiếp tục hỏi LIA hoặc bật theo dõi giá.'});result={confirmedIntent:true};
}
else if(b.action==='dismiss_intent'){if(t.pendingIntent?.id!==b.proposalId)throw new Error('VALIDATION:Đề xuất đã thay đổi.');delete t.pendingIntent;}
else if(b.action==='check'){if(t.status!=='monitoring')throw new Error('VALIDATION:Start monitoring this trip first.');if(t.end<new Date().toISOString().slice(0,10)){t.status='expired';}else {t.offers=makeOffers(t);t.retrieval=retrievalSummary(t);delete t.aiRecommendation;t.checkedAt=new Date().toISOString();const observed=t.offers.slice().sort((a,b)=>a.price-b.price)[0];if(observed){t.history.push({date:new Date().toLocaleDateString('en-AU',{month:'short',day:'numeric'}),price:observed.price});t.history=t.history.slice(-20);}const best=t.offers.filter(o=>o.price<=t.budget).sort((a,b)=>b.score-a.score)[0];if(best&&s.profile.notifications&&!s.notifications.some(n=>n.tripId===t.id&&!n.read)){const reasons=[t.budget>=100000?'no hard budget limit is set':`within your AUD ${t.budget.toLocaleString()} budget`,`${best.baggage} kg baggage included`,`${best.transit}h transit`];if(s.profile.personalize&&s.profile.seat!=='No preference')reasons.push(`${s.profile.seat.toLowerCase()} seat preference saved`);if(s.profile.family)reasons.push('family preference considered');if(s.profile.member)reasons.push(`${best.miles.toLocaleString()} sample Lotusmiles shown`);s.notifications.unshift({id:crypto.randomUUID(),tripId:t.id,text:`Strong sample match: ${t.from} → ${t.to} for AUD ${best.price.toLocaleString()} · ${reasons.slice(0,4).join(' · ')}.`,read:false});}result={matched:!!best,observedPrice:observed?.price??null};}}
else if(b.action==='demo_fare_observation'){if(t.status!=='monitoring')throw new Error('VALIDATION:Start monitoring this trip first.');const baseline=makeOffers(t);if(!baseline.length)throw new Error('VALIDATION:No illustrative option is available for this intent. Relax transit or baggage constraints first.');const candidate=baseline.find(o=>o.score===100)||baseline[0];const targetBelowBudget=Math.max(50,t.budget-20);const simulatedPrice=Math.max(50,Math.min(candidate.price-70,targetBelowBudget));const simulated={...candidate,id:candidate.id+'-OBS',label:'New observed match · demo',price:simulatedPrice,score:100,source:'simulated-demo-observation' as const};t.offers=[simulated,...baseline.filter(o=>o.id!==candidate.id)];t.checkedAt=new Date().toISOString();t.history.push({date:'Demo now',price:simulated.price});t.history=t.history.slice(-20);s.notifications=s.notifications.filter(n=>n.tripId!==t.id);let notificationCreated=false;if(s.profile.notifications){const reasons=[t.budget>=100000?'no hard budget limit is set':`now within your AUD ${t.budget.toLocaleString()} budget`,`${simulated.transit}h transit is within your ${t.transit}h limit`,`${simulated.baggage} kg baggage meets your saved requirement`];s.notifications.unshift({id:crypto.randomUUID(),tripId:t.id,text:`Demo fare observation: ${t.from} → ${t.to} for AUD ${simulated.price.toLocaleString()} · ${reasons.join(' · ')}.`,read:false});notificationCreated=true;}result={matched:true,previousPrice:candidate.price,price:simulated.price,notificationCreated,source:'simulated-demo-observation'};}
else if(b.action==='reset_demo_observation'){t.offers=makeOffers(t);t.retrieval=retrievalSummary(t);delete t.aiRecommendation;t.checkedAt=undefined;t.history=[];s.notifications=s.notifications.filter(n=>n.tripId!==t.id);result={reset:true};}
else if(b.action==='booking'){const offer=t.offers.find(o=>o.id===b.offerId);if(!offer||!b.confirmed)throw new Error('VALIDATION:Review and confirm an available offer.');const seat=z.enum(['Aisle','Window','No preference']).parse(b.seat);const extraBag=!!b.extraBag;const booking={id:crypto.randomUUID(),tripId:t.id,offer,seat,extraBag,total:offer.price+(extraBag?65*t.passengers:0),created:new Date().toISOString(),status:'demo-review-complete'};s.bookings.unshift(booking);result=booking;}
else throw new Error('VALIDATION:Unknown action.');}
const update=await database().prepare('UPDATE workspaces SET payload=?,revision=revision+1 WHERE owner=? AND revision=?').bind(JSON.stringify(s),id,row.revision).run();if(!update.meta.changes)return Response.json({error:'Another update was saved. Refresh before retrying.'},{status:409});return Response.json({state:s,revision:row.revision+1,result});}catch(e){if(e instanceof LlmError)return Response.json({error:e.message,code:e.code},{status:e.status});if(e instanceof z.ZodError)return Response.json({error:'Please check your input.'},{status:400});return failure(e);}}
