export type Intent = {name:string;from:string;to:string;start:string;end:string;budget:number;passengers:number;baggage:number;transit:number;seat:string};
export type Offer = {id:string;datasetId?:string;label:string;price:number;transit:number;hours:number;baggage:number;miles:number;flight:string;score:number;personalizedScore?:number;rankingReasons?:string[];departureTime?:string;arrivalTime?:string;stops?:number;flexibility?:'Basic'|'Standard'|'Flexible';source?:'synthetic-demo-dataset'|'simulated-demo-observation'};
export type PreferenceDimension='price'|'transit'|'journey_time'|'baggage'|'miles';
export type PreferenceEvidenceSource='explicit'|'choice'|'filter'|'booking';
export type PreferenceEvidence={id:string;tripId:string;offerId:string;dimension:PreferenceDimension;created:string;source?:PreferenceEvidenceSource;strength?:number;note?:string};
export type StarterTripMode='unspecified'|'one-way'|'round-trip';
export type StarterDateMode='fixed'|'window';
export type StarterLeg='outbound'|'return';
export type SeatCabin='business'|'economy'|'economy-saver';
export type SeatZone='front'|'middle'|'rear';
export type SeatPosition='Aisle'|'Window'|'Middle';
export type SeatSelection={seat:string;cabin:SeatCabin;zone:SeatZone;position:SeatPosition;recommended?:boolean;reason?:string};
export type RequestedCabin='economy'|'business'|'any';
export type TicketTraveller={name:string;accountHolder?:boolean;seatSelection?:SeatSelection|null};
export type StarterSearchFilters={
  maxPrice?:number|null;
  maxTransit?:number|null;
  minBaggage?:number|null;
  directOnly?:boolean|null;
  requireTransit?:boolean|null;
  transitVia?:string|null;
  excludeChina?:boolean|null;
  sortBy?:'best'|'price'|'duration'|'transit';
  limit?:number;
};
export type StarterSelectedOffer={
  offerId:string;
  departureDate:string;
  departureTime:string;
  arrivalDate:string;
  arrivalTime:string;
  routing:string;
  totalPriceAUD:number;
  totalDurationText:string;
  stops:number;
  transitAirport:string;
  transitCity:string;
  transitMinutes:number;
  baggageKg:number;
  flightReference?:string;
  fareType?:string;
  flexibility?:string;
  selectedAt:string;
};
export type StarterRoundTripCombo={
  id:string;
  outbound:StarterSelectedOffer;
  return:StarterSelectedOffer;
  totalPriceAUD:number;
  totalDurationMinutes:number;
  totalTransitMinutes:number;
  rankingScore:number;
};
export type StarterSuggestedItinerary={
  id:string;
  outbound:StarterSelectedOffer;
  return?:StarterSelectedOffer|null;
  totalPriceAUD:number;
  source:'chat'|'monitoring';
};
export type StarterPendingSuggestion={
  kind:'switch_departure'|'select_offer';
  offerId:string;
  departureDate:string;
  reason:string;
  filters:StarterSearchFilters;
  created:string;
};
export type StarterLastSearch={
  query:string;
  leg?:StarterLeg;
  requestedDate:string|null;
  exactMatchIds:string[];
  nearbyMatchIds:string[];
  nearMissIds:string[];
  recommendedOfferId:string|null;
  offers?:StarterSelectedOffer[];
  filters:StarterSearchFilters;
  searchedAt:string;
};
export type StarterConversation={
  messages:{role:'user'|'assistant';text:string}[];
  draft:Partial<Intent>;
  searchFilters?:StarterSearchFilters;
  pendingSuggestion?:StarterPendingSuggestion;
  selectedOfferId?:string|null; // backwards-compatible alias of outbound
  selectedOffer?:StarterSelectedOffer|null; // backwards-compatible alias of outbound
  selectedOutboundOffer?:StarterSelectedOffer|null;
  selectedReturnOffer?:StarterSelectedOffer|null;
  lastSearch?:StarterLastSearch;
  outboundSearch?:StarterLastSearch;
  returnSearch?:StarterLastSearch;
  roundTripCombos?:StarterRoundTripCombo[];
  tripMode?:StarterTripMode;
  dateMode?:StarterDateMode;
  activeLeg?:StarterLeg;
  returnSuggestionPending?:boolean;
  checkoutStage?:'none'|'offer-payment'|'monitoring';
  suggestedItineraries?:StarterSuggestedItinerary[];
  seatSelection?:SeatSelection|null;
  requestedCabin?:RequestedCabin;
  phase?:'collecting'|'searching'|'awaiting-confirmation'|'selected';
};
export type RetrievalSummary={source:'synthetic-demo-dataset';datasetSize:number;routeMatches:number;shown:number};
export type AiRecommendation={offerId:string;summary:string;reasons:string[];tradeoffs:string[];created:string;model:string};
export type Trip = Intent & {id:string;status:string;selectedOffer?:StarterSelectedOffer|null;selectedReturnOffer?:StarterSelectedOffer|null;searchFilters?:StarterSearchFilters;suggestedItineraries?:StarterSuggestedItinerary[];monitoringSuggestions?:StarterSuggestedItinerary[];seatSelection?:SeatSelection|null;requestedCabin?:RequestedCabin;messages:{role:string;text:string}[];history:{date:string;price:number}[];offers:Offer[];retrieval?:RetrievalSummary;aiRecommendation?:AiRecommendation;checkedAt?:string;feedback?:string;version:number;pendingIntent?:{id:string;patch:Partial<Intent>;baseVersion:number}};
export type CompletedTicket={id:string;reference:string;paidAt:string;status:'paid-demo';from:string;to:string;passengers:number;seat:string;seatSelection?:SeatSelection|null;travellers?:TicketTraveller[];start?:string;end?:string;outbound?:StarterSelectedOffer|null;return?:StarterSelectedOffer|null;directOffer?:Offer|null;extraBag?:boolean;totalPriceAUD:number};
export type MonitoringOpportunity={kind:'monitoring-match';itineraryId?:string|null;offerId?:string|null;price:number;whyNow:string[]};
export type Notification={id:string;tripId:string;text:string;read:boolean;kind?:'trip'|'payment'|'opportunity';ticket?:CompletedTicket;opportunity?:MonitoringOpportunity};
export type State = {trips:Trip[];profile:{name:string;member:boolean;personalize:boolean;notifications:boolean;seat:string;baggage:number;family:boolean;lotusTier?:string;lotusMilesBalance?:number;lotusMilesExpiring?:number};notifications:Notification[];bookings:{id:string;tripId:string;offer:Offer;seat:string;extraBag:boolean;total:number;created:string;status:string}[];preferenceEvidence:PreferenceEvidence[];starter?:StarterConversation};
export const blankIntent:Intent={name:'',from:'SYD',to:'HAN',start:'2026-12-10',end:'2026-12-28',budget:1200,passengers:1,baggage:23,transit:4,seat:'Aisle'};
export function initialState(profileName='Traveller'):State {return {trips:[],profile:{name:profileName,member:false,personalize:false,notifications:true,seat:'Aisle',baggage:23,family:false,lotusTier:'Gold',lotusMilesBalance:24500,lotusMilesExpiring:8000},notifications:[],bookings:[],preferenceEvidence:[]};}
